apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: cert-issuer
spec:
  acme:
    email: mike.pham@proplogix.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-secret
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: media-services
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cert-issuer
spec:
  tls:
    - hosts:
        - guessit.mikepham.net
      secretName: cert-secret
  rules:
    - host: couchdb.mikepham.net
      http:
        paths:
          - backend:
              serviceName: couchdb-svc-couchdb
              servicePort: 5984
---
apiVersion: v1
kind: Service
metadata:
  name: guessit
  namespace: media-services
  annotations:
    external-dns.alpha.kubernetes.io/hostname: guessit.mikepham.net
  labels:
    service: guessit
spec:
  type: ClusterIP
  ports:
    - name: guessit
      port: 5000
  selector:
    app: guessit
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: guessit
  namespace: media-services
spec:
  selector:
    matchLabels:
      app: guessit
  serviceName: guessit
  replicas: 2
  template:
    metadata:
      labels:
        app: guessit
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: guessit
          image: nativecode/guessit:latest
          ports:
            - containerPort: 5000
